# Generated by Django 6.0.7 on 2026-08-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='timesheets/%Y/%m/%d/'),
        ),
    ]
